services:

  app:
    env_file: .env
    container_name: rozario-backend-${RAILS_ENV}
    image: rozario-backend-${RAILS_ENV}
    build:
      context: .
    ports:
      - "127.0.0.1:3000:3000"
    command: sh -c "
      bundle exec rails db:migrate &&
      bundle exec rails s -p 3000"
