name: rozario
services:

  app:
    env_file: .env
    container_name: rozapp
    image: rozapp
    depends_on: [db]
    networks: [default]
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      args:
        RAILS_ENV: ${RAILS_ENV:-production}
    volumes:
      - ${APP_VOLUME:-./public:/app/public}
    ports:
      - 3005:3000
    command: sh -c "
      bundle exec rails db:migrate &&
      bundle exec whenever --update-crontab &&
      rm -f tmp/pids/server.pid &&
      bundle exec rails s -p 3000 -b 0.0.0.0"

  db:
    image: postgres:alpine
    container_name: rozdb
    networks: [default]
    restart: unless-stopped
    environment:
      POSTGRES_USER: rozario
      POSTGRES_PASSWORD: rozpass
      POSTGRES_INITDB_ARGS: --locale=ru_RU.UTF8
    volumes:
      - ./shared/db/postgres:/var/lib/postgresql/data/
    ports:
      - 5432:5432


networks:
  default:
    name: rozario
    driver: bridge
