services:

  app:
    env_file: .env
    build:
      context: .
    ports:
      - "3000:3000"
    command: sh -c "
      bundle exec rails db:migrate &&
      bundle exec rails s -b 0.0.0.0 -p 3000"
