name: Deploy backend (ghcr.io)

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set vars
        run: |
          echo "date=$(date +%d-%m-%Y.%H%M%S)" >> $GITHUB_ENV
          echo "image_name=ghcr.io/${{ github.repository }}-${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          build-args: BUNDLE_WITHOUT=development
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ${{ env.image_name }}:latest
            ${{ env.image_name }}:${{ env.date }}

      - name: Send telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} создал коммит в репозитории ${{ github.repository }}
            Сообщение: ${{ github.event.commits[0].message }}
            https://github.com/${{ github.repository }}/commit/${{github.sha}}

      # - name: Deploy to VPS
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.DEPLOY_HOST }}
      #     username: ${{ secrets.DEPLOY_USER }}
      #     key: ${{ secrets.DEPLOY_SSHKEY }}
      #     script: |
      #       docker login ghcr.io -u ${{ github.repository_owner }} -p ${{ secrets.GITHUB_TOKEN }}
      #       docker compose pull
      #       docker stop ${{ github.repository }}-${{ github.ref_name }} || true
      #       docker system prune -f
      #       docker run -dp 3005:3005 --name ${{ github.event.repository.name }}-${{ github.ref_name }} ${{ env.image_name }}
